### ISSUE TITLE
estimateShipping: Possible to specify "no free shipping" or a specific price tier?

### ISSUE THREAD

**Issue by justanotheramateur** [UltraCart/rest_api#30]
We're trying to disable free shipping for certain users when estimating shipping prices for them.

I know I can log in as them to the API and get the right shipping price for their tier.

Is it possible to avoid that step and specify either the pricing tier directly or a "no free shipping" override?

Thanks!

**Comment by perrytew** [comment]
There's no way to affect pricing without some means of authentication.  Either you authenticate as a merchant or they authenticate as a customer profile.  The only way to specify a pricing tier is through the customer profiles.

The usual means is to check the 'no free shippping' on the pricing tier so that any customers who authenticate and receive that pricing tier's beneficial prices do not also receive the free shipping.  You mention logging in as them -- are you doing a server side checkout, such as with PHP calling the REST API?  Or is this a javascript checkout?

**Comment by justanotheramateur** [comment]
Thank you.

We were able to get around this by:

1. Creating a shared user (pricingChecker)
1. Making a simple PHP proxy (before the rest proxy) that just adds pricingChecker's email and password
1. Returning just the shipping cost from the proxy to javascript. The end-user takes that shipping cost but still checks out with their original cart under their own account.
